### PR TITLE
fix(cli): check that the subsidy vk is set

### LINKED ISSUE #446: Verify local subsidy `.zkey` file with on-chain verifying key
https://github.com/privacy-scaling-explorations/maci/blob/v1/cli/ts/checkVerifyingKey.ts

### PR DESCRIPTION
**Pull request by ctrlc03**
add a check that the subsidy verifying key was set correctly on chain inside the cli command `checkVerifyingKeys`

fix #446

### CODE REVIEW

File: cli/ts/commands/setVerifyingKeys.ts [hunk 1]
```diff
@@ -120,16 +120,17 @@ export const setVerifyingKeys = async (
...
     const ssIntStateTreeDepth = Number(ssMatch[2]);
     const ssVoteOptionTreeDepth = Number(ssMatch[3]);
+
     if (
-      stateTreeDepth !== ssStateTreeDepth ||
-      intStateTreeDepth !== ssIntStateTreeDepth ||
-      voteOptionTreeDepth !== ssVoteOptionTreeDepth
+      Number(stateTreeDepth) !== ssStateTreeDepth ||
+      Number(intStateTreeDepth) !== ssIntStateTreeDepth ||
+      Number(voteOptionTreeDepth) !== ssVoteOptionTreeDepth
```
Comment (kittybest) [inline cli/ts/commands/setVerifyingKeys.ts:127]: Why we need the `Number` here? also same question for L84:89, since I think the input already define them as `number`?

Comment (ctrlc03) [reply cli/ts/commands/setVerifyingKeys.ts]: @kittybest fixed now

**Review by kittybest — APPROVED** [review]
