### PR TITLE
fix(cli): prioritize contract addresses params

### LINKED ISSUE #1039: mergeMessages error: "contractAddresses.json does not exist"
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am not running a deprecated version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

mergeMessages() should not read the contractAddress.json file if maciAddress is provided.

https://github.com/privacy-scaling-explorations/maci/blob/dev/cli/ts/commands/mergeMessages.ts#L34

# Current Behavior

```
Error: [✗] File clrfund/monorepo/contracts/node_modules/maci-cli/build/contractAddresses.json does not exist
      at logError (node_modules/maci-cli/ts/utils/theme.ts:86:9)
      at readJSONFile (node_modules/maci-cli/ts/utils/storage.ts:13:13)
      at readContractAddress (node_modules/maci-cli/ts/utils/storage.ts:41:37)
      at mergeMessages (node_modules/maci-cli/ts/commands/mergeMessages.ts:34:27)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async mergeMaciSubtrees (utils/maci.ts:309:3)
      at async finalizeRound (e2e/index.ts:298:5)
      at async Context.<anonymous> (e2e/index.ts:453:31)
```

# Failure Information

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

- MACI version:
- Firmware Version:
- Operating System:
- SDK version:
- Toolchain version:

## Failure Logs

Please include any relevant log snippets or files here.

### PR DESCRIPTION
**Pull request by ctrlc03**
# Description

Do no throw when the contract addresses file is not present but a contract address has been provided

## Related issue(s)

fix #1039

## Confirmation

- [x] I have read and understand MACI's [contributor guidelines](https://github.com/privacy-scaling-explorations/maci/blob/dev/CONTRIBUTING.md) and [code of conduct](https://github.com/privacy-scaling-explorations/maci/blob/dev/CODE_OF_CONDUCT.md).
- [x] I have read and understand MACI's [GitHub processes](https://github.com/privacy-scaling-explorations/maci/discussions/847).
- [x] I have read and understand MACI's [testing guide](https://maci.pse.dev/docs/testing).

### CODE REVIEW

File: cli/ts/utils/storage.ts [hunk 1]
```diff
@@ -38,7 +38,12 @@ export const storeContractAddress = (contractName: string, address: string): voi
...
  */
 export const readContractAddress = (contractName: string): string => {
-  const contractAddrs = readJSONFile(contractAddressesStore);
+  let contractAddrs: Record<string, string> = {};
+  try {
+    contractAddrs = readJSONFile(contractAddressesStore);
+  } catch (error) {
+    return "";
+  }
   return contractAddrs[contractName] || "";
```
Comment (0xmad) [inline cli/ts/utils/storage.ts:47]:
```suggestion
  try {
    return readJSONFile(contractAddressesStore)[contractName] || "";
  } catch (error) {
    return "";
  }
```

**Review by 0xmad — CHANGES_REQUESTED** [review]
@ctrlc03 thanks, just one comment to fix.

**Review by kittybest — APPROVED** [review]

**Review by 0xmad — APPROVED** [review]
@ctrlc03 thanks!
