### PR TITLE
fix(optimisedmt) - update package to the latest version and generate the correct d.ts file

### LINKED ISSUE #874: Update optimisedmt to the latest version and fix d.ts file
The version of [optimisedmt](https://github.com/weijiekoh/optimisedmt) in use (0.07) is outdated and the d.ts (declarations) file has some mistakes (such as wrong type for the `pathElements` variable).

### PR DESCRIPTION
**Pull request by ctrlc03**
The version of [optimisedmt](https://github.com/weijiekoh/optimisedmt) currently in use is outdated, and the d.ts (declarations) file has some mistakes. This PR fixes these issues (fix #874) by
*  upgrading to version 0.0.9. The upgrade includes adding the `getLeaf(index: number)` and `equals()` methods
* generating a new d.ts directly from the repo's code

### CODE REVIEW

File: crypto/ts/@types/optimisedmt.d.ts [hunk 1]
```diff
@@ -1,25 +1,177 @@
...
     root: bigint;
 
     nextIndex: number;
 
+    leaves: Leaf[];
+
+    zeros: bigint[];
+
+    filledSubtrees: bigint[][];
+    /* eslint-disable-next-line */
```
Comment (0xmad) [inline crypto/ts/@types/optimisedmt.d.ts:28]: You shouldn't use any type and disable it with lint.

File: crypto/ts/@types/optimisedmt.d.ts [hunk 2]
```diff
@@ -1,25 +1,177 @@
...
+    filledPaths: any;
+
+    hashFunc: (leaves: bigint[]) => bigint;
+
+    constructor(
+      _depth: number,
+      _zeroValue: bigint | number,
+      _leavesPerNode: number,
+      _hashFunc: (leaves: bigint[]) => bigint,
```
Comment (0xmad) [inline crypto/ts/@types/optimisedmt.d.ts:37]: Please don't use underscore for variables and params.

**Review by 0xmad — CHANGES_REQUESTED** [review]

File: crypto/ts/@types/optimisedmt.d.ts (hunk 1 above)
Comment (ctrlc03) [reply crypto/ts/@types/optimisedmt.d.ts:28]: This is autogenerated when compiling with declarations: true in tsconfig.json - what would you suggest there? manually generate the d.ts file?

File: crypto/ts/@types/optimisedmt.d.ts (hunk 2 above)
Comment (ctrlc03) [reply crypto/ts/@types/optimisedmt.d.ts:37]: autogenerated file 😓

File: crypto/ts/@types/optimisedmt.d.ts [hunk 3]
```diff
@@ -1,25 +1,177 @@
...
+  export type PathElements = bigint[][];
+  export type Indices = number[];
+  interface MerkleProof {
+    pathElements: PathElements;
+    indices: Indices;
+    depth: number;
+    root: bigint;
+    leaf: Leaf;
+  }
+  export class IncrementalTree {
```
Comment (0xmad) [inline crypto/ts/@types/optimisedmt.d.ts:12]:
```suggestion
  export type Leaf = bigint;
  export type PathElements = bigint[][];
  export type Indices = number[];

  interface MerkleProof {
    pathElements: PathElements;
    indices: Indices;
    depth: number;
    root: bigint;
    leaf: Leaf;
  }
 
  export class IncrementalTree {
```

File: crypto/ts/@types/optimisedmt.d.ts [hunk 4]
```diff
@@ -1,25 +1,177 @@
...
+
+    genMerklePath(_index: number): MerkleProof;
+
+    static verifyMerklePath(_proof: MerkleProof, _hashFunc: (leaves: bigint[]) => bigint): boolean;
+
+    copy(): IncrementalTree;
+
+    equals(t: IncrementalTree): boolean;
+  }
+  export class MultiIncrementalTree {
```
Comment (0xmad) [inline crypto/ts/@types/optimisedmt.d.ts:59]:
```suggestion
  }

  export class MultiIncrementalTree {
```

**Comment by ctrlc03** [comment]
> I've updated the PR text to clearly articulate the specifics of upgrading to optimisedmt version 0.0.9

Thank you

**Review by 0xmad — APPROVED** [review]
@ctrlc03 thanks!
